// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByQfcOgRsHk0ZczR9xLz2zQHmZ48nu0Ds',
    appId: '1:955620905462:web:c2a896b9d03967e803f7d7',
    messagingSenderId: '955620905462',
    projectId: 'flutter-brew-app-1bb00',
    authDomain: 'flutter-brew-app-1bb00.firebaseapp.com',
    storageBucket: 'flutter-brew-app-1bb00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtNhD5fK7Tcei-ggsIxl3uJHjdnFqM_sk',
    appId: '1:955620905462:android:7debd12278a03e5003f7d7',
    messagingSenderId: '955620905462',
    projectId: 'flutter-brew-app-1bb00',
    storageBucket: 'flutter-brew-app-1bb00.appspot.com',
  );
}
